### ISSUE TITLE
Overwriting key-value pair in KVS does not work

### ISSUE THREAD

**Issue by sonjahapp** [openpmix/openpmix#3368]
### What version of the PMIx Reference Library are you using? 
OpenPMIx v5.0.2
PRRTE 3.0.5

### Describe how PMIx was installed 
from a git clone

### Please describe the system on which you are running

* Operating system/version: Rocky Linux release 9.4
* Computer hardware: docker swarm cluster
* Network type:

-----------------------------

## Details of the problem

Hello Ralph,

I noticed that overwriting a key-value pair in the KVS using `PMIx_Put/Commit/Fence/Get` does not work with OpenPMIx 5.0.2. This can be reproduced with the test `test/simple/doubleget.c`.

We did have a somewhat similar issue some time ago for the 4.2 series (see https://github.com/openpmix/openpmix/issues/3201). Though now a process group does not make any difference.

Only if I pass the option `--wait` to the `doubleget` test, I get the updated value on the process that does the wait (`sleep(2)`), but not on the other one:

```console
$ prterun -n 2 ./doubleget
PMIx initialized
Execute fence
Execute fence
prterun-n01-1986@1:0 PMIx_Put on test-key-0 with value ORIG rank 0
prterun-n01-1986@1:1 PMIx_Put on test-key-1 with value ORIG rank 1
prterun-n01-1986@1:0 PMIx_get test-key-1 returned 256 bytes (value ORIG rank 1)
0: obtained data for test-key-1 "ORIG rank 1"
prterun-n01-1986@1:1 PMIx_get test-key-0 returned 256 bytes (value ORIG rank 0)
1: obtained data for test-key-0 "ORIG rank 0"
Execute fence
prterun-n01-1986@1:0 PMIx_Put on test-key-0 with value OVERWRITE rank 0
Execute fence
prterun-n01-1986@1:1 PMIx_Put on test-key-1 with value OVERWRITE rank 1
prterun-n01-1986@1:1 PMIx_get test-key-0 returned 256 bytes (value ORIG rank 0)
1: obtained data for test-key-0 "ORIG rank 0"
prterun-n01-1986@1:0 PMIx_get test-key-1 returned 256 bytes (value ORIG rank 1)
0: obtained data for test-key-1 "ORIG rank 1"
PMIx finalized
```

and with the `--wait`

```console
$ prterun -n 2 ./doubleget --wait
PMIx initialized
Execute fence
prterun-n01-2019@1:0 PMIx_Put on test-key-0 with value ORIG rank 0
Execute fence
prterun-n01-2019@1:1 PMIx_Put on test-key-1 with value ORIG rank 1
prterun-n01-2019@1:0 PMIx_get test-key-1 returned 256 bytes (value ORIG rank 1)
0: obtained data for test-key-1 "ORIG rank 1"
prterun-n01-2019@1:0 PMIx_Put on test-key-0 with value OVERWRITE rank 0
Execute fence
prterun-n01-2019@1:1 PMIx_get test-key-0 returned 256 bytes (value OVERWRITE rank 0)
1: obtained data for test-key-0 "OVERWRITE rank 0"
Execute fence
prterun-n01-2019@1:1 PMIx_Put on test-key-1 with value OVERWRITE rank 1
prterun-n01-2019@1:0 PMIx_get test-key-1 returned 256 bytes (value ORIG rank 1)
0: obtained data for test-key-1 "ORIG rank 1"
PMIx finalized
prterun-n01-2019@1:1 PMIx_get test-key-0 returned 256 bytes (value OVERWRITE rank 0)
1: obtained data for test-key-0 "OVERWRITE rank 0"
```

Do you have any idea what might be causing this?

Thanks a lot for your support!

**Comment by rhc54** [comment]
I suspect the problem lies in the design. We "hold" the exchanged values at the server - this is done to control memory footprint as (in most cases) not every process needs access to every posted value. When proc A requests a value posted by proc B, the server returns _all_ values posted by proc B under the assumption that A will likely request additional values from that proc.

So when you update a value, the update gets held at the server. However, when proc A requests the value again, it will simply return the value it already has in its local storage - it has no reason to believe it needs to ask the server again.

The problem should be resolved by including the `PMIX_GET_REFRESH_CACHE` attribute to the `PMIx_Get` request as that instructs the client library to request a refresh of published data by the server.  Just doing a quick check here showed that this worked.

I'm puzzled by the "wait" option having any impact on this behavior - it shouldn't, and I don't know why it would. I'd have to dig a little deeper to see what that would happen.

I suppose there are improvements one could do to this approach - e.g., have the server automatically send updates to procs that have previously requested data that has changed. Or at least have the server notify a proc that data for another proc changed so the client library knows it should re-request it. However, that would involve significantly increased bookkeeping in the library - not a dealbreaker, but something that merits some consideration.

Fortunately, updating posted values seems a very unusual behavior - I think I've seen it once or twice in the last 20 years. So this might not be a high priority - those apps doing it _know_ they are doing it, and so adding the "refresh" attribute may not be an onerous requirement.

I'd welcome any thoughts on the matter! I don't see an immediate right/wrong answer here.

**Comment by sonjahapp** [comment]
> when proc A requests the value again, it will simply return the value it already has in its local storage - it has no reason to believe it needs to ask the server again.

Is this compliant with the PMIx standard?
I would put the case of no attributes given on `PMIx_Get` into case (3) in Section 5.3 (PMIx 5 standard). So a client should always request the information from the local PMIx server if no attribute was given - and the local server would then need to take an action depending on the rank/location of the target process to provide the requested data. The case you describe could rather fit to cases where the attribute `PMIX_IMMEDIATE` was provided to prevent synchronization of data explicitly.

> The problem should be resolved by including the PMIX_GET_REFRESH_CACHE attribute to the PMIx_Get request as that instructs the client library to request a refresh of published data by the server. Just doing a quick check here showed that this worked.

I cannot confirm that adding the `PMIX_GET_REFRESH_CACHE` attribute helps (at least not for v5.0.2. and PRRTE 3.0.5). I still get the "old" value after the update has been put and committed, even with `PMIX_GET_REFRESH_CACHE`. Might also be a problem of my setup...

Another thought on this attribute: With OpenPMIx 4.2 series it is possible to overwrite key-value pairs in the KVS without `PMIX_GET_REFRESH_CACHE`. I do not see a reason why PMIx programs should adapt their code to change from version 4.2.x to version 5 if there was no corresponding change in the standard w.r.t. `PMIx_Get`. Sure, this would not be a huge change, but one that I would not expect to be necessary since we are using a *standardized* interface. :-)

I've also observed that using the `PMIX_GET_REFRESH_CACHE` attribute on `PMIx_Get` for a key that is requested the first time by a client yields `PMIX_ERR_NOT_FOUND` - even though the key/value pair is definitely available! This is not what I would expect...

> Fortunately, updating posted values seems a very unusual behavior - I think I've seen it once or twice in the last 20 years. So this might not be a high priority - those apps doing it know they are doing it, and so adding the "refresh" attribute may not be an onerous requirement.

Background on why we are using updated values in the KVS: ParaStation MPI uses the KVS to exchange initial connection information of processes during initialization of the MPI library. Since MPI Sessions are allowed to re-init the MPI library (`MPI_Session_finalize` followed by `MPI_Session_init`), we are forced to share the (new, updated) connection information per process again via the KVS. We re-use the same keys to avoid the additional complexity of inventing new keys with a consistent pattern over all processes. It is another question if it is a good idea to use MPI Session re-init after all and probably that does not happen too often in reality. But the MPI standard allows it, so we should support it. So currently this KVS value overwriting problem is breaking our MPI 4.0 support with OpenPMIx 5.

**Comment by rhc54** [comment]
> Is this compliant with the PMIx standard?

I guarantee nobody even thought about it for the Standard. As I said, I've seen that use-case once or twice in 20+ years, so not exactly at the forefront of our thinking. 🤷‍♂️ 

> So a client should always request the information from the local PMIx server if no attribute was given

Ouch - no, you _really_ don't want to do that. The time required to return a value would go up significantly, and that would negatively impact a lot of people.

>  cannot confirm that adding the PMIX_GET_REFRESH_CACHE attribute helps (at least not for v5.0.2. and PRRTE 3.0.5).

Could well be true - I was testing with PMIx master branch. The upcoming v5.0.3 release would behave the same as it has also been updated.

> The case you describe could rather fit to cases where the attribute PMIX_IMMEDIATE was provided to prevent synchronization of data explicitly.

I'm afraid that isn't correct - "immediate" means that if the client cannot find the key in its own memory, it should ask the local server, but the local server shall not pass the request to the host if the local server cannot find the key in its memory. If the client finds the key in its own memory, then that value is returned and the local server is never contacted. Won't help at all with the "refresh" issue.

> With OpenPMIx 4.2 series it is possible to overwrite key-value pairs in the KVS without PMIX_GET_REFRESH_CACHE.

Bit surprised there - certainly was never an explicitly designed behavior. Still, good to know, though I'm a tad concerned that there are hidden problems based on prior discussions.

>  Sure, this would not be a huge change, but one that I would not expect to be necessary since we are using a standardized interface.

Except that this behavior was only mentioned in the Standard in the context of including the "refresh" attribute - which was explicitly added to deal with the case where the app knows or suspects that the posting proc changed the value of a previously used key. Sure, we could address that again in the Standard, though I would challenge them to come up with an acceptable implementation before accepting the change.

> Since MPI Sessions are allowed to re-init the MPI library (MPI_Session_finalize followed by MPI_Session_init), we are forced to share the (new, updated) connection information per process again via the KVS. 

Hmmm...I wonder if that is an MPICH thing? If so, I wonder why they did that? OMPI most definitely does not change its connection info due to a session init. The proc itself remains the same, and it is the proc that holds the connection. Session just provides context over who gets the info from the connection. 🤷‍♂️  But it isn't really important here. I only know that OMPI's session support has no problem with PMIx v5 series - in fact, they rather rely on it due to the "group" operations. Not saying that overrides your situation - just noting that "overwrite" isn't _required_ to support the sessions concept...it has to do with the implementation of that concept.

> So currently this KVS value overwriting problem is breaking our MPI 4.0 support with OpenPMIx 5.

It sounds like you actually mean the "sessions" support and not all of MPI 4.0 - yes? Doesn't really matter, just clarifying.

-------------------------

I hear what you are saying and it has some merit. It will just take some thought as to how to address it. Significantly hurting the performance for the most common use-cases to support what at least for now is an "exception" case isn't really an option, so I'll have to think of some other approach.

Most likely solution will be to add the bookkeeping to alert the client to a change. We had a lot of discussion about this years ago as it creates some significant issues (e.g., race conditions and how to handle updates in shared memory where we return a handle to the data instead of a copy of it). Couldn't come up with any clean solutions, but we can try to revisit it again.

No promises - we can only try, and as I said, it will be awhile before I can get to it. To be honest, probably not something that would be released until sometime next year, barring somebody else picking it up. If they do, probably the best thing would be to start with a recap of the issues we discussed years ago (perhaps on a telecon as well as in an issue, for capture purposes) to avoid re-walking prior failed attempts.

**Comment by rhc54** [comment]
Just in the FWIW category: I checked with the sessions working group and confirmed that MPI_Session_init is supposed to be a completely local operation - i.e., it cannot call `PMIx_Fence` and exchange endpoints across multiple procs.  Doesn't change the merit of your request - just pointing out that it shouldn't be impacting the use-case you mentioned.

**Comment by sonjahapp** [comment]
Thank you very much for the detailed explanations and your time. I really appreciate it!

> Could well be true - I was testing with PMIx master branch. The upcoming v5.0.3 release would behave the same as it has also been updated.

I've repeated the `test/simple/doubleget` tests with `PMIX_GET_REFRESH_CACHE` and version 5.0.3 + PRRTE 3.0.6. Still no luck with getting the updated values with `PMIx_Get`. Is there any specific configure or runtime option required?

> Hmmm...I wonder if that is an MPICH thing? If so, I wonder why they did that?

It sure is. I guess, keeping changes simple to support MPI Sessions is one reason why Session re-init is currently implemented in this way. Using the same workflow as for `MPI_Init`/`MPI_Finalize` internally on `MPI_Session_init`/`MPI_Session_finalize` results in connection infos being exchanged again. This is of course not really a good idea as it is redundant - I agree with you on this point. There is definitely room for improvement. I'm currently looking into this (at least for ParaStation MPI). Avoiding the  additional exchange of connection infos on re-init should not be too complicated to implement. Famous last words... :see_no_evil: 

> It sounds like you actually mean the "sessions" support and not all of MPI 4.0 - yes? Doesn't really matter, just clarifying

Yes, that's what I mean. Sorry for the confusion.

> Most likely solution will be to add the bookkeeping to alert the client to a change. We had a lot of discussion about this years ago as it creates some significant issues (e.g., race conditions and how to handle updates in shared memory where we return a handle to the data instead of a copy of it). Couldn't come up with any clean solutions, but we can try to revisit it again.

A clear documentation of the OpenPMIx KVS behavior w.r.t. overwriting values and in particular the behavior of `PMIx_Put`/`PMIx_Get` in this context would already help a lot. As far as I understood, the current implementation should behave like a "write-once-read-multiple-times" space - unless `PMIX_GET_REFRESH_CACHE` is used on `PMIx_Get`. If this behavior is made clear to users upfront, there is hope that people who touch on corner cases (like me) know what to expect for those. If I've overlooked such documentation, please point me to it.

I can see that adding a solution that allows overwriting "out of the box" might impact performance and needs to be designed carefully. Perhaps a runtime switch to turn it on just when it is really required could help to prevent performance impacts in cases where such a feature is not required. I am open to continue this discussion whenever there is the time for it.

> I checked with the sessions working group and confirmed that MPI_Session_init is supposed to be a completely local operation - i.e., it cannot call `PMIx_Fence` and exchange endpoints across multiple procs. Doesn't change the merit of your request - just pointing out that it shouldn't be impacting the use-case you mentioned.

Mhh... In the MPI standard it says "Session instantiation is intended to be a lightweight operation.". It does not explicitly define session init as "completely local". It seems to be a matter of interpretation of "lightweight" here. A fence during `MPI_Session_init` might not be a good/ efficient idea - but it is also not explicitly forbidden.

*(Side note: I'll be out of office until late July.)*

**Comment by rhc54** [comment]
> Mhh... In the MPI standard it says "Session instantiation is intended to be a lightweight operation.". It does not explicitly define session init as "completely local". It seems to be a matter of interpretation of "lightweight" here. A fence during `MPI_Session_init` might not be a good/ efficient idea - but it is also not explicitly forbidden.

They probably need to update the language - according to the working group, the operation is required to be purely "local". Somewhat equivalent in theory to spawning a thread - all done strictly within the process itself.

> A clear documentation of the OpenPMIx KVS behavior w.r.t. overwriting values and in particular the behavior of PMIx_Put/PMIx_Get in this context would already help a lot.

I can try to get to that - being retired puts a longer response time on such things 😄 

> I've repeated the test/simple/doubleget tests with PMIX_GET_REFRESH_CACHE and version 5.0.3 + PRRTE 3.0.6. Still no luck with getting the updated values with PMIx_Get. Is there any specific configure or runtime option required?

Nothing specific at all - it works every time for me with the master branch. I'll have to check to see if something failed to make it over to the release branch.

> (Side note: I'll be out of office until late July.)

Have fun!!

**Comment by rhc54** [comment]
> Mhh... In the MPI standard it says "Session instantiation is intended to be a lightweight operation.". It does not explicitly define session init as "completely local". It seems to be a matter of interpretation of "lightweight" here. A fence during `MPI_Session_init` might not be a good/ efficient idea - but it is also not explicitly forbidden.

@hppritcha I'd have to agree that "lightweight" doesn't translate to "local", at least to me. Is there an update coming to the MPI Standard to clarify the intent (I found the "lightweight" comment in v4.1)?

**Comment by rhc54** [comment]
@sonjahapp Sorry for the long silence - been busy with other things, fighting some health issues, etc. Regardless, I have given this matter some thought and have a few findings to share.

First, I found that `PMIX_GET_REFRESH_CACHE` is indeed working correctly. You can check it out with the `test/simple/doubleget` test:
```shell
$ ./simptest -n 2 -e ./doubleget --refresh
Testing version OpenPMIx 6.0.0a1, repo rev: v1.1.3-4066-g05ffb2d8 (PMIx Standard: 4.1, Stable ABI: 0.0, Provisional ABI: 0.0)
Collecting inventory
Inventory collected: 0
PMIx initialized
foobar:1 PMIx_Put on test-key-1 with value ORIG rank 1
Execute fence
foobar:0 PMIx_Put on test-key-0 with value ORIG rank 0
Execute fence
foobar:0 PMIx_get test-key-1 returned 256 bytes (value ORIG rank 1)
foobar:1 PMIx_get test-key-0 returned 256 bytes (value ORIG rank 0)
1: obtained data for test-key-0 "ORIG rank 0"
0: obtained data for test-key-1 "ORIG rank 1"
foobar:0 PMIx_Put on test-key-0 with value OVERWRITE rank 0
Execute fence
foobar:1 PMIx_Put on test-key-1 with value OVERWRITE rank 1
Execute fence
foobar:1 PMIx_get test-key-0 returned 256 bytes (value OVERWRITE rank 0)
1: obtained data for test-key-0 "OVERWRITE rank 0"
foobar:0 PMIx_get test-key-1 returned 256 bytes (value OVERWRITE rank 1)
0: obtained data for test-key-1 "OVERWRITE rank 1"
PMIx finalized
SIMPTEST: Model event handler called with status -147(PMIX_MODEL_DECLARED)
	pmix.pgm.model:	PMIX
	pmix.mdl.name:	test
	pmix.evname:	SIMPTEST-MODEL
Test finished OK!
$
```
Note that failing to provide `--refresh` means we do not pass `PMIX_GET_REFRESH_CACHE`, and we therefore get the "orig" value again.

One thing to note here: refresh cache is a purely _local_ operation. In other words, the client's cache is refreshed from its local server - we do not query a remote server to get an update of any value pushed by one of its clients. Thus, the value must have been locally updated before "refresh" will return an updated value.

I also walked through the rationale again for not supporting updates of previously published keys, and it remains as previously stated. It creates a race condition that cannot be resolved. I have to think about whether we should even support a "refresh cache" operation as that implies that we do support such updates. IIRC, the thought was to support the case where the app _knows_ it circulated updated info and simply wants to retrieve it. In that limited case, I suppose it makes some sense - though may lead to broader confusion.

I'll close this now as I see no way to fix it for you - if your app "knows" that it did a fence and updated values, then "refresh cache" should resolve the problem. You might need to update PMIx to get it to work - could be a bug in an earlier release. I have verified it works on master branch for now.

**Comment by rhc54** [comment]
I confirmed that the head of the v5.0 branch also works correctly, so I believe this has been resolved.

**Comment by sonjahapp** [comment]
Hi Ralph!

thanks a lot for the effort! :pray: 

Based on our earlier discussion and your recent findings we are currently exploring an alternative solution for our problem that does not need overwriting of values in the KVS. Using the "refresh cache" attribute is one of the options that we are investigating.
